version: "3.8"

services:
  react-app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
